en: "en"
vn: "vi"
link_home: "https://www.railstutorial.org/"
link_help: "https://www.railstutorial.org/help"
link_book: "https://www.railstutorial.org/book"
link_contact: "https://www.railstutorial.org/contact"
link_learn: "https://www.learnenough.com/"
link_new: "http://news.railstutorial.org/"
MH: "http://www.michaelhartl.com/"
max_length:
  name: 50
  email: 225
  password: 6
